<a href="https://colab.research.google.com/github/ASBRUC/DSPS_ABruce/blob/main/Labs/earthquake_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
earthquakes = pd.read_csv("https://raw.githubusercontent.com/fedhere/DSPS_FBianco/refs/heads/main/data/earthquakes.csv",
            sep=r"\s+")

In [3]:
earthquakes.shape #shows rows, cols

(70798, 13)

In [4]:
earthquakes.head(); #show top (parameter) rows
earthquakes.tail() #show bottom (parameter) rows

,#YYY/MM/DD,HH:mm:SS.ss,ET,GT,MAG,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
70793,2002/12/29,19:37:24.56,eq,l,2.21,l,35.31400,-118.66767,3.7,A,9874709,25,948
70794,2002/12/29,20:17:33.40,eq,l,2.02,l,35.32133,-118.66000,1.8,A,9874745,48,245
70795,2002/12/29,20:21:28.73,eq,l,2.07,l,35.32150,-118.66617,1.9,A,9874749,53,277
70796,2002/12/30,21:51:52.55,eq,l,2.31,l,35.31867,-118.66250,1.5,A,9875017,66,404
70797,2002/12/30,23:38:49.79,eq,l,2.05,l,35.31450,-118.66333,1.9,A,9875061,54,283

In [5]:
earthquakes.columns #shows all col names

Index(['#YYY/MM/DD', 'HH:mm:SS.ss', 'ET', 'GT', 'MAG', 'M', 'LAT', 'LON',
       'DEPTH', 'Q', 'EVID', 'NPH', 'NGRM'],
      dtype='object')

In [6]:
earthquakes = earthquakes[['#YYY/MM/DD', 'HH:mm:SS.ss','MAG']]

In [7]:
earthquakes.dtypes #show data types of each variable

#YYY/MM/DD      object
HH:mm:SS.ss     object
MAG            float64
dtype: object

In [8]:
from datetime import time
earthquakes.rename({"#YYY/MM/DD": "date","HH:mm:SS.ss": "time","MAG": "mag"},axis = 1, inplace=True) #{} is for dictionaries, axis = 1 to rename by col

In [9]:
earthquakes.describe()

                mag
count  70798.000000
mean       2.417826
std        0.407683
min        2.000000
25%        2.120000
50%        2.300000
75%        2.590000
max        7.100000

In [12]:
earthquakes["newdates"] = earthquakes["date"].map(pd.to_datetime) #map applies the function to all elements in a series

In [14]:
earthquakes["datetime"] = earthquakes["date"] + " " + earthquakes["time"]
earthquakes["datetime"]

0        1984/01/01 01:30:57.52
1        1984/01/01 05:31:34.16
2        1984/01/01 06:59:05.14
3        1984/01/01 11:10:25.29
4        1984/01/01 19:38:19.79
                  ...
70793    2002/12/29 19:37:24.56
70794    2002/12/29 20:17:33.40
70795    2002/12/29 20:21:28.73
70796    2002/12/30 21:51:52.55
70797    2002/12/30 23:38:49.79
Name: datetime, Length: 70798, dtype: object

In [23]:
for i in earthquakes.index:
  if earthquakes.loc[i, "datetime"].endswith('60.00'):
    earthquakes.loc[i, "datetime"] = earthquakes.loc[i, "datetime"][:6] + "59,99"

In [24]:
earthquakes["newdatetime"] = earthquakes["datetime"].map(pd.to_datetime)

In [31]:
earthquakes["newdatetime"].std()
earthquakes["newdatetime"].mean()
earthquakes["newdatetime"].diff() #takes difference from last point to current point

0                          NaT
1       0 days 04:00:36.640000
2       0 days 01:27:30.980000
3       0 days 04:11:20.150000
4       0 days 08:27:54.500000
                 ...
70793   0 days 00:00:30.140000
70794   0 days 00:40:08.840000
70795   0 days 00:03:55.330000
70796   1 days 01:30:23.820000
70797   0 days 01:46:57.240000
Name: newdatetime, Length: 70798, dtype: timedelta64[ns]